### ISSUE TITLE
Outdated For 1.15+

### ISSUE THREAD

**Issue by DiscultDev** [NerdHubMC/FOML#4]
I don't know if the mod is still being made but it isn't supported in 1.15+ because of the way you do Sprites now, just thought I should let the developer(s) know so if they wanted to they can fix it.

**Comment by alothmanmoe** [comment]
I've pretty much stopped modding so i won't be updating this. That being said i believe someone else said they're gonna take a look at doing that. If not Upcraft said he'd do it later on.

**Comment by ashpieboop** [comment]
Fixed by #5 , pending publication (once it's in the maven repository, I'll make a github release).
